### ISSUE TITLE
package does not exist 'import org.opencv.face.Face'

### ISSUE THREAD

**Issue by santhosh827** [andreaiacono/OpenCVDemo#1]
Sir i need your help. i am implementing your code but it is showing 
import org.opencv.face.Face;
import org.opencv.face.FaceRecognizer;
import org.opencv.imgcodecs.Imgcodecs; 
package does not exist error. I have added opencv-249.jar in classpath.
and i need to anyother lib file in classpath?

**Comment by andreaiacono** [comment]
Hi,
as you can see from the description of the project, I'm using OpenCV 3.1.0 and not OpenCV 2.4.9. If you follow the Installation instructions of the project you shouldn't have this kind of problem. 

HTH,
Andrea

**Comment by van562** [comment]
Hi Andrea,
which versions? http://opencv.org/downloads.html

**Comment by andreaiacono** [comment]
Downloading the compiled package from the opencv.org site will not work, you have to compile it yourself. Please, read the installation section on the project page, it's all explained there.

**Comment by santhosh827** [comment]
Hi Sir,
Thank you for your reply now i downloaded and installed opencv-3.1.0 in my system(Windows-7  32 bit OS) 
still now i am facing 
import org.opencv.face.Face;
import org.opencv.face.FaceRecognizer;
package does not exist error. 

But import org.opencv.imgcodecs.Imgcodecs is working,
i added opencv-3.1.0.jar in classpath 
in opencv-3.1.0.jar ' Imgcodecs' calss is available with same name of package
but  Face and FaceRecognizer class is not available.

**Comment by andreaiacono** [comment]
Github doesn't work like this. You can't do what you're doing now: not reading _all_ the project page and start asking every single issue you face.  
I'm happy to provide help, but only if you read _all_ the installation section of the project: it's all explained there.
