### ISSUE TITLE
Information about licensing for the project

### ISSUE THREAD

**Issue by razvan100** [andreaiacono/OpenCVDemo#2]
Hello @andreaiacono 

  My name is Razvan, I am a Computer Engineering student and came across this project as it uses OpenCV. I would like to use parts of it in my master thesis, referencing it.
  Will you allow this? as I haven't found any information about this in the repository.

Thank you!

**Comment by andreaiacono** [comment]
Hi Razvan,
feel free to use whatever you need of this project and good luck with your master thesis! :-)

**Comment by razvan100** [comment]
Thank you Andrea!

Have a nice day!
